name: Recent GitHub Activity

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */6 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          GH_USERNAME: harshitpaunikar1
          MAX_LINES: 8
          COMMIT_MSG: "chore: update recent GitHub activity"
